import { mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import StyleDictionary from 'style-dictionary';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, '..');
export const distDir = resolve(root, 'dist');
const tokensPath = resolve(root, 'src/tokens.json');

const HEADER = `/**
 * Generated by @acme/design-tokens. Do not edit by hand.
 * Source: packages/design-tokens/src/tokens.json
 */
`;

const raw = JSON.parse(readFileSync(tokensPath, 'utf8'));

/** Splits the single tokens.json ingestion file into a resolvable per-mode tree. */
export function modeTree(mode) {
  const { color, ...rest } = raw;
  return { ...rest, color: color[mode] };
}

StyleDictionary.registerFormat({
  name: 'acme/tailwind-preset',
  format: ({ dictionary }) => {
    const colors = {};
    const spacing = {};
    const borderRadius = {};
    const fontFamily = {};
    const fontSize = {};
    const fontWeight = {};

    for (const token of dictionary.allTokens) {
      const [category] = token.path;

      if (category === 'color') {
        const key = token.name.replace(/^color-/, '');
        colors[key] = `var(--${token.name})`;
      } else if (category === 'spacing') {
        // Token keys use `_` instead of `.` (Style Dictionary treats literal
        // dots in key names as path separators) — restore Tailwind's `0.5`
        // convention here, at the boundary, instead of in the source data.
        const key = token.path.slice(1).join('-').replace(/_/g, '.');
        spacing[key] = token.$value;
      } else if (category === 'radius') {
        borderRadius[token.path.slice(1).join('-')] = token.$value;
      } else if (category === 'font') {
        const [, sub] = token.path;
        const key = token.path.slice(2).join('-');
        if (sub === 'family') fontFamily[key] = token.$value;
        if (sub === 'size') fontSize[key] = token.$value;
        if (sub === 'weight') fontWeight[key] = token.$value;
      }
      // `palette` tokens are intentionally not exposed here — consumers
      // should build on semantic color tokens, not raw primitives.
    }

    return `${HEADER}
/** @type {import('tailwindcss').Config} */
export const tailwindPreset = {
	darkMode: ["class", '[data-theme="dark"]'],
	theme: {
		extend: {
			colors: ${JSON.stringify(colors, null, 2)},
			spacing: ${JSON.stringify(spacing, null, 2)},
			borderRadius: ${JSON.stringify(borderRadius, null, 2)},
			fontFamily: ${JSON.stringify(fontFamily, null, 2)},
			fontSize: ${JSON.stringify(fontSize, null, 2)},
			fontWeight: ${JSON.stringify(fontWeight, null, 2)},
		},
	},
};

export default tailwindPreset;
`;
  },
});

StyleDictionary.registerFormat({
  name: 'acme/native-color-vars-json',
  format: ({ dictionary }) => {
    const vars = {};
    for (const token of dictionary.allTokens) {
      if (token.path[0] === 'color') {
        vars[`--${token.name}`] = token.$value;
      }
    }
    return JSON.stringify(vars, null, 2);
  },
});

async function buildCss(mode, selector, filter) {
  const sd = new StyleDictionary({
    tokens: modeTree(mode),
    platforms: {
      css: {
        transformGroup: 'css',
        buildPath: `${distDir}/`,
        files: [
          {
            destination: `_variables.${mode}.css`,
            format: 'css/variables',
            filter,
            // `palette` tokens (the reference targets) are filtered out of
            // this output on purpose, so references must resolve to their
            // final value here rather than pointing at an undeclared var().
            options: { selector, outputReferences: false },
          },
        ],
      },
    },
  });
  await sd.buildAllPlatforms();
}

async function buildNativeColors(mode) {
  const sd = new StyleDictionary({
    tokens: modeTree(mode),
    platforms: {
      native: {
        transformGroup: 'css',
        buildPath: `${distDir}/`,
        files: [
          {
            destination: `_theme.${mode}.json`,
            format: 'acme/native-color-vars-json',
            filter: (token) => token.path[0] === 'color',
          },
        ],
      },
    },
  });
  await sd.buildAllPlatforms();
}

async function buildTailwindPreset() {
  const sd = new StyleDictionary({
    tokens: modeTree('light'),
    platforms: {
      tailwind: {
        transformGroup: 'css',
        buildPath: `${distDir}/`,
        files: [{ destination: 'tailwind-preset.ts', format: 'acme/tailwind-preset' }],
      },
    },
  });
  await sd.buildAllPlatforms();
}

function mergeCssVariables() {
  const light = readFileSync(`${distDir}/_variables.light.css`, 'utf8');
  const dark = readFileSync(`${distDir}/_variables.dark.css`, 'utf8');
  writeFileSync(`${distDir}/variables.css`, `${HEADER}\n${light}\n${dark}`);
  rmSync(`${distDir}/_variables.light.css`);
  rmSync(`${distDir}/_variables.dark.css`);
}

function mergeNativeTheme() {
  const light = JSON.parse(readFileSync(`${distDir}/_theme.light.json`, 'utf8'));
  const dark = JSON.parse(readFileSync(`${distDir}/_theme.dark.json`, 'utf8'));
  const content = `${HEADER}
/**
 * NativeWind CSS-variable maps. Register the active set at your app root with
 * NativeWind's \`vars()\` helper, e.g. \`<View style={vars(isDark ? darkVars : lightVars)}>\`.
 */
export const lightVars = ${JSON.stringify(light, null, 2)} as const;

export const darkVars = ${JSON.stringify(dark, null, 2)} as const;

export const nativeTheme = { light: lightVars, dark: darkVars } as const;

export default nativeTheme;
`;
  writeFileSync(`${distDir}/theme.native.ts`, content);
  rmSync(`${distDir}/_theme.light.json`);
  rmSync(`${distDir}/_theme.dark.json`);
}

export async function buildTokens() {
  rmSync(distDir, { recursive: true, force: true });
  mkdirSync(distDir, { recursive: true });

  await buildCss('light', ':root', (token) => token.path[0] !== 'palette');
  await buildCss('dark', '[data-theme="dark"]', (token) => token.path[0] === 'color');
  mergeCssVariables();

  await buildNativeColors('light');
  await buildNativeColors('dark');
  mergeNativeTheme();

  await buildTailwindPreset();

  console.log('Built dist/variables.css, dist/tailwind-preset.ts, dist/theme.native.ts');
}

const isMain = import.meta.url === `file://${process.argv[1]}`;
if (isMain) {
  await buildTokens();
}
